[pytest]
DJANGO_SETTINGS_MODULE = app.infrastructure.config.settings_test
pythonpath = src src/app/infrastructure

python_files = test_*.py
python_classes = Test
python_functions = test_

markers =
    unit: testes unitários de domínio e aplicação (sem banco de dados)
    integration: testes de integração com banco de dados (SQLite in-memory)

addopts =
    --strict-markers
    -q
