[pytest]
DJANGO_SETTINGS_MODULE = {{PACKAGE_NAME}}.infrastructure.config.settings_test
pythonpath = src src/{{PACKAGE_NAME}}/infrastructure

python_files = test_*.py
python_classes = Test
python_functions = test_

markers =
    unit: testes unitários de domínio e aplicação (sem banco de dados)
    integration: testes de integração com banco de dados (SQLite in-memory)

addopts =
    --strict-markers
    -q
